# Generated by Django 5.2.4 on 2025-07-31 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('url', models.URLField(help_text='The fully qualified ID of this entry.', max_length=512, primary_key=True, serialize=False)),
                ('serial', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('github_event_id', models.CharField(blank=True, db_index=True, help_text='The unique ID of the GitHub event, if this entry was imported.', max_length=50, null=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('text/plain', 'Plain text'), ('text/markdown', 'Markdown'), ('application/base64', 'Base64'), ('image/png;base64', 'PNG image'), ('image/jpeg;base64', 'JPEG image')], max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends only'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL, to_field='url')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('url', models.URLField(help_text='The fully qualified ID of this comment.', max_length=512, primary_key=True, serialize=False)),
                ('serial', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('comment', models.TextField()),
                ('content_type', models.CharField(default='text/plain', max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='url')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='entries.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('url', models.URLField(help_text='The fully qualified ID of this like.', max_length=512, primary_key=True, serialize=False)),
                ('serial', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('object_id', models.CharField(max_length=512)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='url')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
